const test=require('node:test');const assert=require('node:assert/strict');const vm=require('node:vm');const fs=require('node:fs');const path=require('node:path');
const context=vm.createContext({Intl,Date,console,document:{addEventListener(){}},currentOverview:{tesla_settings:{export_rule:'pv_only'}}});
vm.runInContext(fs.readFileSync(path.join(__dirname,'../automations.js'),'utf8'),context);
const plain=x=>JSON.parse(JSON.stringify(x));
test('iOS pausing rules exclude one-off schedules and Power Hour',()=>{for(const type of ['ev','battery','price','power','solar','edf_power_perks'])assert.equal(context.automationPausable({payload:{trigger:{type}}}),true);assert.equal(context.automationPausable({payload:{trigger:{type:'schedule'}},repeat_until:null}),false);assert.equal(context.automationPausable({payload:{trigger:{type:'schedule'}},repeat_until:7258118400}),true);assert.equal(context.automationPausable({payload:{trigger:{type:'event_import_cap'}}}),false);});
test('next schedule follows site time and weekday across daylight-saving changes',()=>{const run=(now,time,days)=>new Date(context.automationNextTime(time,days,'Europe/London',Date.parse(now)/1000)*1000).toISOString();assert.equal(run('2026-09-27T08:00:00Z','18:30',[1]),'2026-09-27T17:30:00.000Z');assert.equal(run('2026-03-28T23:00:00Z','02:30',[1]),'2026-03-29T01:30:00.000Z');assert.equal(run('2026-10-24T23:00:00Z','02:30',[1]),'2026-10-25T02:30:00.000Z');assert.throws(()=>run('2026-09-27T08:00:00Z','18:30',[]),/Choose/);});
test('edit keeps ID, grouped actions, windows and trigger values',()=>{const e={siteKey:'site',rule:{id:'original',paused:true},draft:{name:'Reserve',trigger:{type:'price',source:'import',condition:'below',value:.123,unit:'GBP_per_kwh',time_window:{enabled:true,start:'23:00',end:'05:00'}},actions:[{type:'adjust_backup_reserve',backup_reserve_percent:100},{type:'home_assistant_event',event_name:'reserve_change',message:'Ready'}]}};const result=plain(context.automationSaveBody(e,'Europe/London',1790496000));assert.equal(result.automation_id,'original');assert.deepEqual(result.payload.trigger,e.draft.trigger);assert.deepEqual(result.payload.actions,e.draft.actions);assert.equal(result.repeat_until,null);assert.equal(result.paused,undefined);});
test('notification kind follows the selected trigger and expired repeats are rejected',()=>{const e={siteKey:'site',draft:{name:'',trigger:{type:'edf_power_perks',event:'starts'},actions:[{type:'notification_only',notification_kind:'battery_soc'}]}};assert.equal(context.automationSaveBody(e,'Europe/London').payload.actions[0].notification_kind,'edf_power_perks');e.draft.trigger={type:'schedule',hour:18,minute:0,days:[1,2,3,4,5,6,7]};e.repeating=true;e.repeatUntil=1;assert.throws(()=>context.automationSaveBody(e,'Europe/London'),/end date/);});
test('mutually exclusive actions and four-action limit use iOS choices',()=>{const options=plain(context.automationAvailableActions({trigger:{type:'battery'},actions:[{type:'adjust_backup_reserve'}]}));assert.equal(options.adjust_backup_reserve,undefined);assert.equal(options.freeze_battery_soc,undefined);assert.equal(options.notification_only,undefined);assert.ok(options.set_op_mode);assert.equal(context.automationAvailableActions({trigger:{type:'schedule'},actions:[]}).notification_only,undefined);});
